_announcement/All Announcements.md

Please approve the changes. Thanks.

Adding Calendar of Events to announcement page

---

_ccas/Clubs & Societies/AVA Club.md
_ccas/Clubs & Societies/MediaComm Club.md
_ccas/Performing Arts/Performing Arts.md
_ccas/Sports & Games/Badminton.md
_ccas/Sports & Games/Floorball.md
_ccas/Sports & Games/Netball.md
_ccas/Sports & Games/Soccer.md
_ccas/Sports & Games/Volleyball.md
_ccas/Uniformed Group/Boys' Brigade.md
_ccas/Uniformed Group/Girls' Brigade.md
_ccas/Uniformed Group/NCC.md
_ccas/Uniformed Group/NPCC.md

Updated CCA teachers in charge and training schedule

---

_about-us/Our VMV.md

To correct our school Vision/Mission

---

_about-us/Our Staff.md
_announcement/All Announcements.md
_curriculum/English.md

Updated teacher's name and title

---

_outreach/Sexuality Education.md

Update of Sex Education

---

_outreach/Sexuality Education.md

As per Wei Jin's request. For your approval, please.

Update file: Sexuality Education (some minor changes of content)

---

_ccas/CCA.md
_ccas/Clubs & Societies/AVA Club.md

For your approval please. Thanks.

Updated CCA's page to correct the minor typo

---

_ccas/Clubs & Societies/AVA Club.md

Updated teachers-in-charge

---

_announcement/All Announcements.md

For your review and approval. Thanks.

To publish the Collection of SGC for Graduates from Sec 4TE5 (2022)

---

_announcement/All Announcements.md

To add back one record of missing event and one date typo error. For your approval please.

Update Term 2 calendar of events 2023

---

_announcement/All Announcements.md

For your review and approval, thanks.

To add the announcement for the collection of SGC for Graduates from Sec 4 Express (2022)

---

_announcement/All Announcements.md

For your review and approval, thanks.

Publish the collection of SGC for Graduates from Sec 4NA and 5NA - 2022

---

_about-us/Advisory Committee.md
_about-us/Contact Us.md
_about-us/Our Staff.md
_about-us/School Management Committee.md

Update the bookshop and school uniform supplier details

---

_announcement/All Announcements.md

For your review & approval, thanks.

Added Calender of events for Term 3

---

_announcement/All Announcements.md

Add the announcement about The Straits Times School Pocket Money Fund 2024 application.

---

_partners-of-smbss/Parent Support Group.md

Remove PSG link

---

_about-us/Our People/Non Teaching Staff.md

As requested by AM, I added her name (Ms. Eileen So) but not the full name since the rest of the staff also didn't do so. For your approval, thanks.

To add AM's name into Our People > Non-teaching staff page in the school website. 

---

_about-us/Our People/Non Teaching Staff.md
_about-us/Our People/School Management Committee.md

To add AM's name into School Management Committee in the school website. 

---

_about-us/Calendar of School Events.md

Updated calendar to reflect term 2

Update School Calendar

---

_announcements/All Announcements.md

Added the announcement of Collection of SGC for 2023 graduates for Mdm Tay

---

index.md

For your review & approval, thanks.

Updated the link on the homepage, hero section's text and hyperlink to link to Direct School Admission Exercise 2024 page as per Hengguang's request. 

---

_about-us/Our People/Teaching Staff.md
_ccas/Clubs & Societies/AVA Club.md

Request by teacher to edit & fix broken link under 'AVA club' & corrected Joe's name under the 'Teaching Staff' page. Thank you.

Edited CCA (AVA Club) & Teaching Staff Page

---

index.md

Update banner to link to open house

Update home page banner to link to open house

---

_announcements/All Announcements.md

Hi Boon Keong, for your approval & publishing. Thank you.

N Level Result Announcement Update

---

_smbss-experience/Distinctive Programmes/PEARL.md

Hi Alan & Boon Keong, I've briefly updated the PDLP section.
- Removing of info relating to Mobile Guardian & Zoom
- Included a link to the Google site that I've created for PLDs
Please let me know if you'd like to include/remove any other information to the page. Thanks.

Updating of PDLP page

---

_about-us/School Advisory Committee.md

Update SAC member

---

_about-us/School Advisory Committee.md

Edit to SAC member

---

_about-us/Our People/School Management Committee.md
_about-us/Our People/Teaching Staff.md
resource/announcements/_posts/2025-06-28-file-2025 Sem 2 Class Timetable.md

FTs/Co-FTs Deployment Update
